apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
  labels:
    app: test-2
    applicationId: app_c387b0d9-4301-47cc-aeff-48b1158ba03d
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
