apiVersion: v1
kind: Namespace
metadata:
  name: test-1-prod
  labels:
    environment-id: env_30c0e506-7b19-4434-9dc7-3fe5a32fd99d
    project-id: project_262978d9-3aec-4b41-855c-77f08f9b3a42
    project-name: test-1
    environment-name: prod
    organization-id: org_bf6668ae-7e34-40b4-a1d8-8f3d391114a2
