apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
    applicationId: app_70ff56e6-27bb-4677-82bf-44830ec9bb95
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
