apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: test-app
    applicationId: app_70ff56e6-27bb-4677-82bf-44830ec9bb95
    version: v0.0.1
  name: test-app
spec:
  selector:
    app: test-app
